FROM ubuntu:22.04

# 업데이트 및 업그레이드
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# 표준 시간대 UTC로 수정
RUN apt-get update && apt install tzdata -y
ENV TZ="UTC"

RUN apt-get install -y curl nano wget software-properties-common locales

RUN locale-gen en_US.UTF-8

# ping, net-tools, nslookup 설치 
RUN apt-get install -y iputils-ping net-tools dnsutils passwd

RUN apt-get install -y ansible sshpass openssh-client && \
    apt-get clean

CMD /bin/bash